baseURL = 'https://lau.yeeyu.org/'
languageCode = 'en-us'
title = 'Yiyu Liu (刘祎禹)'

theme = "soho"
copyright = "Yiyu Liu"
googleAnalytics = "G-8RHH1RWLJN"
hasCJKLanguage = true

[params]
images = ["images/profile.webp"]
profilePicture = "images/profile.webp"
showVeritasBanner = true

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/LauYeeYu"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/LauYeeYu"

  [[params.socialIcons]]
  icon = "fa-orcid"
  title = "ORCID"
  url = "https://orcid.org/0009-0000-6852-1978"

  [[params.socialIcons]]
  icon = "fa fa-envelope"
  title = "Email"
  url = "mailto:yiyuliu@g.harvard.edu"

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
